### ISSUE TITLE
Toy example included?

### ISSUE THREAD

**Issue by Ni-Ar** [nf-core/proteomicslfq#102]
Hi, 

I was wondering if this pipeline comes with a test dataset included?
Something small to have a look at the generated output and make sure it runs smoothly.

Thanks!
Nicco

**Comment by Zethson** [comment]
Hi @Ni-Ar,

yes.
Please use the profile `test` for this purpose.

Run the pipeline e.g. as
`
nextflow run nf-core/proteomicslfq -profile singularity,test`

**Comment by jpfeuffer** [comment]
Actually, the `test_full` profile has nicer output since it is a real ground-truth dataset. Have a look at that too.

**Comment by Ni-Ar** [comment]
Okay I tried the `test` profile at the moment and it looks okay. Thanks!

**Comment by Ni-Ar** [comment]
I tried the pipeline with the `test_full` profile and I get this error message:

````
 The exit status of the task that caused the workflow execution to fail was: -

The full error message is reported below:

SIGHUP
````
