### ISSUE TITLE
How to specify to run on my institute's HPC cluster?

### ISSUE THREAD

**Issue by Ni-Ar** [nf-core/proteomicslfq#103]
Hi,

I downloaded your pipeline on my local institution cluster with:

```
git clone https://github.com/nf-core/proteomicslfq.git
```

and can successfully run the pipeline with the `test` example and it even works with nextflow tower after adding my nextflow access token in the `nextflow.config` file.

```
cd proteomicslfq
nextflow run main.nf -profile singularity,test -with-tower --outdir test
```

I realised all the jobs are running on the login cluster of my institution (CRG ANT-CLUSTER), while I'd like to run the pipeline the on the high performance computing cluster of my institution (CRG, Barcelona, Spain). To do this I would usually use `qsub` for example If I'd like to run `STAR`

```
qsub -q <QUEU_NAME> -V -cwd -pe smp <NUM_PROCESSES> \
         -l virtual_free=<NUM_RAM>G -l h_rt=<NUM_HOURS>:05:15 \
         -N STAR_TEST \
         -b y\
         STAR bla bla bla
```

In the past I achieve such a thing with nextflow simply by writing something like this in the `nextflow.config` file:

```
process {
      container = '/path/to/envs/or/container'
     	queue='long-sl7,short-sl7'
     	memory='12G'
     	cpus='4'
     	time='6h'
 }
```

Now, to my understanding in this pipeline `nextflow.config` file there's no such information cause the process requirments are specified in the `conf/*.config` files so that one has more flexibility on the processes demands, plus everything is nicely controlled by the `check_max()` function, which is fine for me.

I also read in the documentation that:

> The pipeline also dynamically loads configurations from [https://github.com/nf-core/configs](https://github.com/nf-core/configs) when it runs, making multiple config profiles for various institutional clusters available at run time

however, I believe there's no config profile available for my institutional cluster, or I'm not doing it right (`-profile crg` failes for example).

So now what is the best practise to follow? Should I make my own `my_institute.config` to run on my institutional cluster or there's something that I'm doing wrong?

Thanks,
Nicco

```
> nextflow info

  Version: 20.07.1 build 5412
  Created: 24-07-2020 15:18 UTC (17:18 CEST)
  System: Linux 3.10.0-514.16.1.el7.x86_64
  Runtime: Groovy 2.5.11 on OpenJDK 64-Bit Server VM 1.8.0_131-b11
  Encoding: UTF-8 (UTF-8)
```

**Comment by Zethson** [comment]
Dear @Ni-Ar,

all available configs can be found [here](https://github.com/nf-core/configs/tree/master/conf).
If there's no matching config for the CRC, then I would like to suggest that you read [Adding new configs](https://github.com/nf-core/configs#adding-a-new-config) and add one.

If you have questions feel free to ping me.

Cheers
Lukas

**Comment by Ni-Ar** [comment]
Hi @Zethson,

thanks for you reply. I'm afraid there's CRG config (even though it seems weird as nextflow was originally developed here in this institute). Anyway, is there no half-way solution? I mean I honestly believe I lack the competence and skill to make my institution's config "available at run-time to all nf-core pipelines". (Let's face it, I'm a n00b). So, I guess I could use `-c` for a local custom config I could write, no?

**Comment by Zethson** [comment]
Yes, I was surprised too haha. I'll see whether I can dig something up from them.

But yes of course. You can as you mention just supply your own local config using `-c`.

**Comment by jpfeuffer** [comment]
Hi!

Of course, you can do that. It would even be the first step for making it public anyway ;)
Usually, I split my profiles in three parts:
- One institutional profile which specifies, which cluster is used, which max capacities it has, and other specific information of the HPC environment. See the public institution profiles for an example.
- One data size profile, which refines the default requested resources for the different process types we have, based on the size of your data. The default may not be enough for very large datasets. We intend to do some smart resource estimation in the next releases. See [here](https://github.com/nf-core/proteomicslfq/blob/master/conf/base.config#L25) for the defaults.
- And optionally a dataset profile with the actual parameters of the pipeline specific to the used dataset (in case you want to reuse or share the analysis with the dataset).

**Comment by jpfeuffer** [comment]
The last two actually could/should be combined.

**Comment by Ni-Ar** [comment]
In the end I made a new config in the `baseDir` which is a sort of merged `nextflow.config` + `conf/base.config` and add:

```
process {
  queue='long-sl7,short-sl7'
  executor='sge'
  penv='smp'
  cpus = { check_max( 2 * task.attempt, 'cpus' ) }
  memory = { check_max( 8.GB * task.attempt, 'memory' ) }
  time = { check_max( 4.h * task.attempt, 'time' ) }
 
_omissis_

  withName:get_software_versions {
    cache = false
  }
}
```
And now it can run on the HPC.

Thanks a lot for the support!

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/98002973-79557e00-1dee-11eb-8a98-305de8760bb0.png)

@lucacozzuto

**Comment by lucacozzuto** [comment]
Eing? :)
