### ISSUE TITLE
ProteomicsLFQ exit status 6

### ISSUE THREAD

**Issue by Ni-Ar** [nf-core/proteomicslfq#105]
Hi again,

I run the pipeline like this:
```
nextflow run main.nf
		 -profile singularity
		 --input ../data/raw/*.raw 
		 --database ../data/reference/proteome/Mouse_prot_database.fasta
		 --expdesign ../data/exp_design/experimental_design.tsv
		 --outdir res_MsdClvg3
		 --allowed_missed_cleavages 3
		 -c crg.config
		 --add_decoys
```
These processes succeed:

```
N E X T F L O W  ~  version 20.07.1
Launching `main.nf` [curious_galileo] - revision: 18f2d39694
executor >  sge (11)
[5d/b8a76b] process > raw_file_conversion (1)         [100%] 1 of 1 ✔
[-        ] process > mzml_indexing                   -
[9a/582f45] process > generate_decoy_database (1)     [100%] 1 of 1 ✔
[-        ] process > openms_peakpicker               -
[-        ] process > search_engine_msgf              -
[72/3160ac] process > search_engine_comet (1)         [100%] 1 of 1 ✔
[00/86f81b] process > index_peptides (1)              [100%] 1 of 1 ✔
[06/51a0d1] process > extract_percolator_features (1) [100%] 1 of 1 ✔
[80/2f443c] process > percolator (1)                  [100%] 1 of 1 ✔
[-        ] process > fdr_idpep                       -
[-        ] process > idpep                           -
[bc/c907dd] process > idscoreswitcher_to_qval (1)     [100%] 1 of 1 ✔
[-        ] process > consensusid                     -
[-        ] process > fdr_consensusid                 -
[42/abfd67] process > idfilter (1)                    [100%] 1 of 1 ✔
[-        ] process > idscoreswitcher_for_luciphor    -
[-        ] process > luciphor                        -
[89/e158d3] process > proteomicslfq (1)               [100%] 1 of 1, failed: 1 ✘
[-        ] process > msstats                         -
[-        ] process > ptxqc                           -
[f4/6023bc] process > get_software_versions           [100%] 1 of 1 ✔
[31/9e5f72] process > output_documentation            [100%] 1 of 1 ✔
```

But I get this  error:

```
Error executing process > 'proteomicslfq (1)'

Caused by:
  Process `proteomicslfq (1)` terminated with an error exit status (6)

Command executed:

  ProteomicsLFQ -in file1.mzML \
                -ids file1_comet_idx_feat_perc_switched_filter.idXML \
                -design experimental_design.tsv \
                -fasta Mouse_prot_database_decoy.fasta \
                -protein_inference aggregation \
                -quantification_method feature_intensity \
                -targeted_only true \
                -mass_recalibration false \
                -transfer_ids false \
                -protein_quantification unique_peptides \
                -out out.mzTab \
                -threads 12 \
                -out_msstats out.csv \
                -out_cxml out.consensusXML \
                -proteinFDR 0.05 \
                -debug 0 \
                > proteomicslfq.log

Command exit status:
  6

Command output:
  (empty)
```

How can I check the meaning of an `exit status 6`?

**Comment by Zethson** [comment]
I tried looking at the ProteomicsLFQ OpenMS source code but found it hard to find which exit status this is supposed to be.

@timosachsenberg can you help here, maybe?

**Comment by jpfeuffer** [comment]
Exit codes are here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h#L157

This would mean "illegal parameter".

But it is often hard to say where the exit status actually came from. It could also be from the containerization software, or from the scheduler, or from the OS.

It would be better if you could upload the log file in the workspace of the failed process. Nextflow should have told you which folder it is, right after the messages you posted.

**Comment by Ni-Ar** [comment]
If I look inside `work/89/e158d3a4b127294b1798ce2f640885` and open the file `proteomicslfq.log` it says:

```
Invalid parameter: Spectra files provided as input need to match the ones in the experimental design file.
```

I double checked and my experimental design file indeed contains the full path the `.raw` files.

**Comment by Ni-Ar** [comment]
Ah maybe the problem is that I provide `file1.raw` in the experimental design table while here `proteomicslfq` has `-in file1.mzML` ?

**Comment by jpfeuffer** [comment]
I am almost certain that we only care about the basename since we often expect converted files but it is worth a try.

What could be the culprit, is that we currently expect ALL of the files in the experimental design to be present, so unfortunately I think you cannot yet specify a full experiment in the design and then analyze only a subset (here: one file). You would need to filter the design as well.

@timosachsenberg We discussed that multiple times before I think.

**Comment by Ni-Ar** [comment]
I never wanted to specify only a subset. I wanted to quantify the proteins in all my `.raw` files, that's why the experimental design contains all the files. 
What would you recommend trying? 
One experimental design per file and launch the pipeline on each individual file? I have 6 samples so I could do that easily.

**Comment by jpfeuffer** [comment]
Ah! It feels like it did not pick up every raw file then.

`--input ../data/raw/*.raw `

Should yield at least as many "raw_file_conversion" steps as there were raw files recognized by the pipeline. In your case, it only started one process: `[5d/b8a76b] process > raw_file_conversion (1)         [100%] 1 of 1 ✔`
which means that it probably did only 'match' one "*.raw" file in that folder.

**Comment by Ni-Ar** [comment]
Uhm... that is very weird as the path really shows all 6 `raw` files.

```
ll ../data/raw/*.raw

../data/raw/file1.raw
../data/raw/file2.raw
../data/raw/file3.raw
../data/raw/file4.raw
../data/raw/file5.raw
../data/raw/file6.raw
```
I think I should give it another try then. I'm cleaning up everything and launch the pipeline again.

**Comment by Ni-Ar** [comment]
In the `.nextflow.log` I check that the command identifies all the input files and it in fact managed correctly:

```
head .nextflow.log
Nov-08 17:25:03.820 [main] DEBUG nextflow.cli.Launcher - $> 
nextflow run main.nf -profile singularity --input ../data/raw/file1.raw ../data/raw/file2.raw ../data/raw/file3.raw ../data/raw/file4.raw ../data/raw/file5.raw ../data/raw/file6.raw --database ../data/reference/proteome/Mouse_prot_database.fasta --expdesign ../data/exp_design/experimental_design.tsv --outdir res_MsdClcg3 --allowed_missed_cleavages 3 -c crg.config --add_decoys

Nov-08 17:25:04.011 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.07.1
Nov-08 17:25:04.040 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [zen_albattani] - revision: 18f2d39694
Nov-08 17:25:04.072 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: proteomicslfq/nextflow.config
Nov-08 17:25:04.075 [main] DEBUG nextflow.config.ConfigBuilder - User config file: proteomicslfq/crg.config
...
``` 
But for some weird reasone nextflow runs only on one sample! 
(The first one)

```
[a6/6abb89] process > raw_file_conversion (1)         [100%] 1 of 1 ✔
[-        ] process > mzml_indexing                   -
[ab/e841f0] process > generate_decoy_database (1)     [100%] 1 of 1 ✔
[-        ] process > openms_peakpicker               -
[-        ] process > search_engine_msgf              -
[75/8af8a7] process > search_engine_comet (1)         [100%] 1 of 1 ✔
[63/5ea7de] process > index_peptides (1)              [100%] 1 of 1 ✔
[bb/38ec7d] process > extract_percolator_features (1) [100%] 1 of 1 ✔
[3e/94b118] process > percolator (1)                  [100%] 1 of 1 ✔
[-        ] process > fdr_idpep                       -
[-        ] process > idpep                           -
[2d/88a2d0] process > idscoreswitcher_to_qval (1)     [100%] 1 of 1 ✔
[-        ] process > consensusid                     -
[-        ] process > fdr_consensusid                 -
[f4/f24c30] process > idfilter (1)                    [100%] 1 of 1 ✔
[-        ] process > idscoreswitcher_for_luciphor    -
[-        ] process > luciphor                        -
[0a/6f6976] process > proteomicslfq (1)               [100%] 1 of 1, failed: 1 ✘
[-        ] process > msstats                         -
[-        ] process > ptxqc                           -
[33/d7b772] process > get_software_versions           [100%] 1 of 1 ✔
[52/66d28b] process > output_documentation            [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
```

And it gives me the same error of before. 

```
-[nf-core/proteomicslfq] Pipeline completed with errors-
Error executing process > 'proteomicslfq (1)'

Caused by:
  Process `proteomicslfq (1)` terminated with an error exit status (6)

Command executed:

  ProteomicsLFQ -in file1.mzML \
                -ids file1_comet_idx_feat_perc_switched_filter.idXML \
                -design experimental_design.tsv \
                -fasta Mouse_prot_database_decoy.fasta \
                -protein_inference aggregation \
                -quantification_method feature_intensity \
                -targeted_only true \
                -mass_recalibration false \
                -transfer_ids false \
                -protein_quantification unique_peptides \
                -out out.mzTab \
                -threads 12 \
                -out_msstats out.csv \
                -out_cxml out.consensusXML \
                -proteinFDR 0.05 \
                -debug 0 \
                > proteomicslfq.log

Command exit status:
  6

Command output:
  (empty)

Work dir:
work/0a/6f6976cdc2ae3001d79638134a8aa8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
````

How come?

**Comment by jpfeuffer** [comment]
Hmm.. Can you try to put quotes around the wildcard expression? It might be that your shell already expands the arguments and nextflow then only picks the first.

**Comment by Ni-Ar** [comment]
Okay `--input "../data/raw/*.raw"` makes it run on all 6 samples.

_However_, I still get the same `exit status 6` error from `ProteomicsLFQ` when running on all samples 😔

```
Error executing process > 'proteomicslfq (1)'

Caused by:
  Process `proteomicslfq (1)` terminated with an error exit status (6)

Command executed:

  ProteomicsLFQ -in file1.mzML file2.mzML  file3.mzML  file4.mzML  file5.mzML  file6.mzML \
                -ids file1_comet_idx_feat_perc_switched_filter.idXML file2_comet_idx_feat_perc_switched_filter.idXML file3_comet_idx_feat_perc_switched_filter.idXML file4_comet_idx_feat_perc_switched_filter.idXML file5_comet_idx_feat_perc_switched_filter.idXML file6_comet_idx_feat_perc_switched_filter.idXML \
                -design experimental_design.tsv \
                -fasta Mouse_prot_database_decoy.fasta \
                -protein_inference aggregation \
                -quantification_method feature_intensity \
                -targeted_only true \
                -mass_recalibration false \
                -transfer_ids false \
                -protein_quantification unique_peptides \
                -out out.mzTab \
                -threads 12 \
                -out_msstats out.csv \
                -out_cxml out.consensusXML \
                -proteinFDR 0.05 \
                -debug 0 \
                > proteomicslfq.log

Command exit status:
  6

Command output:
  (empty)

Work dir:
work/9f/53bcb4f3b030136dbfa938c360936d
```
 And if I check the log

```
cat work/9f/53bcb4f3b030136dbfa938c360936d/proteomicslfq.log 
Invalid parameter: Spectra files provided as input need to match the ones in the experimental design file.
```

**Comment by timosachsenberg** [comment]
can you post the experimental design file?

**Comment by Ni-Ar** [comment]
It's like this:

| Fraction_Group | Fraction | Spectra_Filepath                 | Label | MSstats_Condition | MSstats_BioReplicate | 
|----------------|----------|----------------------------------|-------|-------------------|----------------------|
| 1              | 1        | /full/path/to/data/raw/file1.raw | 1     | WT                | 1                    |   
| 2              | 1        | /full/path/to/data/raw/file2.raw | 1     | WT                | 2                    |   
| 3              | 1        | /full/path/to/data/raw/file3.raw | 1     | WT                | 3                    |   
| 4              | 1        | /full/path/to/data/raw/file4.raw | 1     | KO                | 1                    |   
| 5              | 1        | /full/path/to/data/raw/file5.raw | 1     | KO                | 2                    |   
| 6              | 1        | /full/path/to/data/raw/file6.raw | 1     | KO                | 3                    |

**Comment by timosachsenberg** [comment]
file1.mzML file2.mzML  file3.mzML  file4.mzML  file5.mzML  file6.mzML
but in the experimental design there are the path to the raw files

**Comment by Ni-Ar** [comment]
> file1.mzML file2.mzML file3.mzML file4.mzML file5.mzML file6.mzML
> but in the experimental design there are the path to the raw files

Yes because I input raw files and the pipeline does the conversation. I was told that the everything is done using the `basename`. I'm now trying to change the experimental design table with `.mzML` extension.

**Comment by timosachsenberg** [comment]
Yes I am pretty sure that it will not look at the extension but it may look at the path

**Comment by timosachsenberg** [comment]
Ok, we checked and the tool expects the extension after the conversion (mzML).
The automated conversion from raw to mzML was only added recently, and we do not yet update the experimental design internally to match it. We will open an issue to fix that problem in the future.

**Comment by jpfeuffer** [comment]
Sorry, for the confusion, it was a misunderstanding of the phrase `basename` from my side!
The meaning of `basename` for the tool (and actually in most other use cases on Linux) is indeed the filename **with** extension.

https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/SYSTEM/File.cpp#L312

We will provide an automatic conversion of the filenames in the experimental design in the conversion step in the future to address #107

**Comment by Ni-Ar** [comment]
If I create a design table with the full path to "fake" `.mzML` converted files like this one:

| Fraction_Group | Fraction | Spectra_Filepath                 | Label | MSstats_Condition | MSstats_BioReplicate | 
|----------------|----------|----------------------------------|-------|-------------------|----------------------|
| 1              | 1        | /full/path/to/data/raw/file1.mzML | 1     | WT                | 1                    |   
| 2              | 1        | /full/path/to/data/raw/file2.mzML | 1     | WT                | 2                    |   
| 3              | 1        | /full/path/to/data/raw/file3.mzML | 1     | WT                | 3                    |   
| 4              | 1        | /full/path/to/data/raw/file4.mzML | 1     | KO                | 1                    |   
| 5              | 1        | /full/path/to/data/raw/file5.mzML | 1     | KO                | 2                    |   
| 6              | 1        | /full/path/to/data/raw/file6.mzML| 1     | KO                | 3                    |   

The pipeline returns the following error:

```
Error executing process > 'proteomicslfq (1)'

Caused by:
  Process `proteomicslfq (1)` terminated with an error exit status (6)

Command executed:

  ProteomicsLFQ -in file1.mzML file2.mzML  file3.mzML  file4.mzML  file5.mzML  file6.mzML \
                -ids file1_comet_idx_feat_perc_switched_filter.idXML file2_comet_idx_feat_perc_switched_filter.idXML file3_comet_idx_feat_perc_switched_filter.idXML file4_comet_idx_feat_perc_switched_filter.idXML file5_comet_idx_feat_perc_switched_filter.idXML file6_comet_idx_feat_perc_switched_filter.idXML \
                -design experimental_design.tsv \
                -fasta Mouse_prot_database_decoy.fasta \
                -protein_inference aggregation \
                -quantification_method feature_intensity \
                -targeted_only true \
                -mass_recalibration false \
                -transfer_ids false \
                -protein_quantification unique_peptides \
                -out out.mzTab \
                -threads 12 \
                -out_msstats out.csv \
                -out_cxml out.consensusXML \
                -proteinFDR 0.05 \
                -debug 0 \
                > proteomicslfq.log

Command exit status:
  1

Command output:
  (empty)

Command error:
  /opt/conda/conda-bld/openms-meta_1601515042055/work/src/utils/ProteomicsLFQ.cpp(1555): MzML file in experimental design file '/full/path/to/data/raw/sample1.mzML' not passed as 'in' parameter.
  Note: relative paths in the experimental design file are resolved relative to the design file path. 
  Use absolute paths or make sure the design file is in the same path as the mzML files.

Work dir:
work/a9/a1da9142c66acd672fd4c7ef8d4d39
````

And if fact the error is:
```
cat work/a9/a1da9142c66acd672fd4c7ef8d4d39/proteomicslfq.log 
Error: File not found (the file '/full/path/to/data/raw/file1.mzML' could not be found)
```

Instead if I use an experimental design table **without the full path** and the samples with a "fake" `.mzML` extension like this one:

| Fraction_Group | Fraction | Spectra_Filepath                 | Label | MSstats_Condition | MSstats_BioReplicate | 
|----------------|----------|----------------------------------|-------|-------------------|----------------------|
| 1              | 1        | file1.mzML | 1     | WT                | 1                    |   
| 2              | 1        | file2.mzML | 1     | WT                | 2                    |   
| 3              | 1        | file3.mzML | 1     | WT                | 3                    |   
| 4              | 1        | file4.mzML | 1     | KO                | 1                    |   
| 5              | 1        | file5.mzML | 1     | KO                | 2                    |   
| 6              | 1        | file6.mzML| 1     | KO                | 3                    |   

The pipeline succeed and there were no errors!
Hurray!

**Comment by Zethson** [comment]
Great to hear!  Monday, 09 November 2020, 06:24PM +01:00 from Ni-Ar  notifications@github.com :

**Comment by timosachsenberg** [comment]
Thanks! We will fix that.
