### ISSUE TITLE
Question: potential error in experimental design of aws testdata

### ISSUE THREAD

**Issue by timosachsenberg** [nf-core/proteomicslfq#175]
https://raw.githubusercontent.com/nf-core/test-datasets/proteomicslfq/testdata-aws/experimental_design_short.tsv

Fails for a student because the file path for the high conentration is the same.

Error: Unexpected internal error ((Path, Label) combination can only appear once)

**Comment by tillenglert** [comment]
Same goes for this exp design:
https://github.com/nf-core/test-datasets/blob/d03ba6452685739e2110aab26e604f9da54a282c/testdata-aws/experimental_design_short_urls.tsv

In this case also the URLs changed to:

'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_2500amol_R1.raw',
'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_2500amol_R2.raw',
'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_2500amol_R3.raw',
'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_50000amol_R1.raw',
'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_50000amol_R2.raw',
'ftp://ftp.pride.ebi.ac.uk/pride-archive/2015/12/PXD001819/UPS1_50000amol_R3.raw'

**Comment by timosachsenberg** [comment]
or was that because of AWS test restrictions and we set a test flag to overwrite that?

**Comment by jpfeuffer** [comment]
This was probably a copy paste error. I think we should use all replicates.
The test for no duplicates is just new.

**Comment by ypriverol** [comment]
@timosachsenberg @jpfeuffer I have tested this week the quantms label free. See the results here http://ftp.pride.ebi.ac.uk/pride/data/proteomes/proteogenomics/benchmakrs/PXD000279/

**Comment by jpfeuffer** [comment]
Fixed.
