### ISSUE TITLE
Error executing process > 'proteomicslfq (1)'

### ISSUE THREAD

**Issue by matteopilz** [nf-core/proteomicslfq#177]
The proteomicslfq process crashed with following error message:

Error executing process > 'proteomicslfq (1)'

Caused by:
  Process `proteomicslfq (1)` terminated with an error exit status (8)

[proteomicslfq.log](https://github.com/nf-core/proteomicslfq/files/7692282/proteomicslfq.log)

**Comment by jpfeuffer** [comment]
This is mainly an OpenMS problem. I will create an issue there.
