### ISSUE TITLE
get_software_versions (error 127)

### ISSUE THREAD

**Issue by JannikSchneider12** [nf-core/proteomicslfq#196]
Hello,

I am new to WSL and also to nextflow and I wanted to run the pipeline in WSL. However I always get this error:

Error executing process > 'get_software_versions'

Caused by:
Process get_software_versions terminated with an error exit status (127)

I am not sure how I can solve this. It seems like the command is not available in my WSL, although I checked it ?

So sudo find . -name get_software_versions gives me this:
./get_software_versions

I am using Ubuntu and WSL2.

Thanks for your time and help

**Comment by jpfeuffer** [comment]
Hi!

`get_software_versions` is a nextflow process. It is not necessarily an executable or script on your computer with the same name.

I think you need to find some more output for us to help. Look through your logs in your nextflow folder and the workspace.

Which profile are you using? What was your nextflow call?

To be honest it was a) never tested on WSL and b) this pipeline is kind of superseded by the mightier but a bit more complex `quantms` which has an LFQ branch.

**Comment by JannikSchneider12** [comment]
Hey,

Okay thanks for the clarification. 

I am executing it in the root user, so root:~ is prompted in WSL when I am running the "nextflow run" command.

This is the output, that I get:
-------------------------------------------------------------------------------------------------------------------------------
[nf-core/proteomicslfq] Pipeline completed with errors-
WARN: Failed to render execution report -- see the log file for details
WARN: Failed to render execution timeline -- see the log file for details
Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 1.0.0 > v_pipeline.txt
  echo 22.10.7 > v_nextflow.txt
  ThermoRawFileParser.sh --version &> v_thermorawfileparser.txt
  echo $(FileConverter 2>&1) > v_fileconverter.txt || true
  echo $(DecoyDatabase 2>&1) > v_decoydatabase.txt || true
  echo $(MSGFPlusAdapter 2>&1) > v_msgfplusadapter.txt || true
  echo $(msgf_plus 2>&1) > v_msgfplus.txt || true
  echo $(CometAdapter 2>&1) > v_cometadapter.txt || true
  echo $(comet 2>&1) > v_comet.txt || true
  echo $(PeptideIndexer 2>&1) > v_peptideindexer.txt || true
  echo $(PSMFeatureExtractor 2>&1) > v_psmfeatureextractor.txt || true
  echo $(PercolatorAdapter 2>&1) > v_percolatoradapter.txt || true
  percolator -h &> v_percolator.txt
  echo $(IDFilter 2>&1) > v_idfilter.txt || true
  echo $(IDScoreSwitcher 2>&1) > v_idscoreswitcher.txt || true
  echo $(FalseDiscoveryRate 2>&1) > v_falsediscoveryrate.txt || true
  echo $(IDPosteriorErrorProbability 2>&1) > v_idposteriorerrorprobability.txt || true
  echo $(ProteomicsLFQ 2>&1) > v_proteomicslfq.txt || true
  echo 1.0.0 &> v_msstats_plfq.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Work dir:
  /root/work/c7/9356fe54e031af55c067e4fc592367
  ----------------------------------------------------------------------------------------------------------------------------------
  
  If I look into the work directory, I only see the folders "0c  49  5c  6d  8c  af  fa" for the process. I actually dont know how to see a log there?
  
  And if I run the command "nextflow log", I only see this information for every time I tried executing the pipeline:
  
  2023-03-03 11:17:42     1m 23s          intergalactic_austin    ERR     43c77e50c9      26934126-c2a0-4810-9eba-38daf9752d71    nextflow run nf-core/proteomicslfq -profile test -c nextflow.config, docker
  
  I hope that helps or that I can somehow find more information.
  
  Thanks for your time and help

**Comment by jpfeuffer** [comment]
How exactly did you run `nextflow run`? Was this your full command?

Why don't you follow the introduction page? https://nf-co.re/proteomicslfq?q=proteomicslfq

If you navigate into the c7/... folders, there should be logs like ".command.log" or something.

**Comment by JannikSchneider12** [comment]
Hello,

My full command is "nextflow run nf-core/proteomicslfq -profile test -c nextflow.config, docker" and in the nextflow config file I only added the use of memory, but I also left it out and only ran "nextflow run nf-core/proteomicslfq -profile test, docker". 

I looked at the work/c7 directory and only found one document that contains something. This was the text:

"/root/work/c7/9356fe54e031af55c067e4fc592367/.command.sh: line 4: ThermoRawFileParser.sh: command not found"

And the file was called "v_thermorawfileparser.txt"

Again thanks for your time and help

**Comment by jpfeuffer** [comment]
I think all your commands are wrong. Docker is a profile so it needs to be on the "profile" option. And as usual with command line interfaces, if you do not surround your arguments with quotes, a whitespace will start a new option. You should have gotten quite some warnings about those  superfluous arguments if I am not mistaken.

The correct command line that you probably want is:
`nextflow run nf-core/proteomicslfq -profile "test,docker"`.

**Comment by jpfeuffer** [comment]
Without the docker profile nextflow will assume all the tools are installed directly on your computer.
This is what you saw in the logs. Great that you found them!

**Comment by JannikSchneider12** [comment]
Hey,

Now I understand. Many thanks. I tested it and it worked. I actually didn't got any errors/warnings when using my old command. 

Thanks for your help
