### ISSUE TITLE
Investigate caching issues with SDRF file option

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/proteomicslfq#43]
Probably has something to do with the fact, that we parse the inputs from a file here.
Which get directly loaded into input "path"s to processes. And the paths are potentially even URIs.
I don't know. We have to ask somewhere I guess.

@Zethson any idea?

**Comment by Zethson** [comment]
I don't quite understand the problem.

When do the caching issues arise?

I guess that this may be more suited for the nextflow gitter chat or the nf-core help channel.
Unlikely that I know more here ...
