### ISSUE TITLE
Multiple search engines

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/proteomicslfq#45]
Although this is kind of an open research question and sometimes might even have a negative impact (not only on runtime), there are requests for merging multiple search engine results.
In OpenMS we currently have two choices:
- [x] IDPEP -> Merge -> ConsensusID
- [x] Percolator with MultiSE feature extraction

Alternatives are welcome as well.

Also, we could extend the support for other search engines, e.g.:
- XTandem
- Mascot

**Comment by jpfeuffer** [comment]
ConsensusID version is implemented.

**Comment by ypriverol** [comment]
This has been extensively tested. I will close the issue.
