### ISSUE TITLE
Error in conversion of raw -> mzML in project PXD018682

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#52]
The project PXD018682 when is converted from RAW -> mzML only captured `profile` MS2 spectra and not the `centroid`. This is probably an error in the TRFP. 

One of the files examples is here:  
[03.raw](http://ftp.pride.ebi.ac.uk/pride/data/archive/2020/04/PXD018682/03.raw)

**Comment by ypriverol** [comment]
@timosachsenberg @julianus The error will remain for a while because is in the API. It will take some time to be solved. I will add this as a low-priority issue.

**Comment by jpfeuffer** [comment]
@ypriverol Can this be closed with the upgrade to the new TRFP version?
