### ISSUE TITLE
Add citations to the used tools somewhere

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/proteomicslfq#57]

**Comment by Zethson** [comment]
https://github.com/nf-core/imcyto

just has a top level CITATION.md, which is referenced at the bottom of the README

**Comment by ypriverol** [comment]
I can take this issue @jpfeuffer @Zethson if you assign it to me.

**Comment by Zethson** [comment]
@ypriverol 
Are you not a nf-core member yet?

If not it's time to get you added :)

**Comment by ypriverol** [comment]
Please, feel free to add me to nf-core ;)

**Comment by Zethson** [comment]
You should have received an invite now.

**Comment by ypriverol** [comment]
PR https://github.com/nf-core/proteomicslfq/pull/60

**Comment by ypriverol** [comment]
@Zethson I didn't get the invitation.

**Comment by MaxUlysse** [comment]
Can you try again?

**Comment by ypriverol** [comment]
DONE
