### ISSUE TITLE
running comet without posterior error probabilities crashed

### ISSUE THREAD

**Issue by Leon-Bichmann** [nf-core/proteomicslfq#6]
./nextflow run nf-core/proteomicslfq --spectra "MZML/* 50000 *mzML" --database uniprot_yeast_reviewed_isoforms_ups1_crap.fasta_td.fasta --expdesign experimental_design_short.tsv --search_engine comet -profile singularity -r dev

**Comment by jpfeuffer** [comment]
Can you try again and report the error if it still exists?

**Comment by Leon-Bichmann** [comment]
I'll give it another try with the latest version

**Comment by Leon-Bichmann** [comment]
Hey it is working but seems to fail at the msstats step now. I posted the full error in the slack group.
