### ISSUE TITLE
ENSEMBL stop codons not working

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#62]
We need to find a way that ensemble stop codons can be processed by PeptideIndexer 
. Sequences like: 

- GGGGG*SSSTR

**Comment by jpfeuffer** [comment]
See the corresponding OpenMS issue https://github.com/OpenMS/OpenMS/issues/4670

**Comment by cbielow** [comment]
so how should this be interpreted?
a) pretend the * does not exist (simply delete it before searching)
b) treat it as a peptide start/end site (as Comet seems to do)

**Comment by ypriverol** [comment]
I think we can check how different search engines handle it and propagate the behavior. Let me double-check with Peptideshacker guys that use almost 5 search-engines.

**Comment by ypriverol** [comment]
This has been solving in the PRIDE side using a tool.
