### ISSUE TITLE
PTM not working in Comet (Met-loss+acetyl (Protein N-term))

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#65]
Error executing process > 'search_engine_comet (1)'

Caused by:
  Process `search_engine_comet (1)` terminated with an error exit status (6)

Command executed:

  CometAdapter  -in 020320_TiO2_Phospho.mzML \
                -out 020320_TiO2_Phospho.idXML \
                -threads 4 \
                -database "total_decoy.fasta" \
                -instrument low_res \
                -allowed_missed_cleavages 2 \
                -num_hits 1 \
                -num_enzyme_termini fully \
                -enzyme "Trypsin" \
                -precursor_charge 2:4 \
                -fixed_modifications 'Carbamidomethyl (C)' \
                -variable_modifications 'Acetyl (Protein N-term)' 'Met-loss+acetyl (Protein N-term)' 'Oxidation (M)' 'Phospho (S)' 'Phospho (T)' 'Phospho (Y)' \
                -max_variable_mods_in_peptide 3 \
                -precursor_mass_tolerance 10 \
                -precursor_error_units ppm \
                -fragment_bin_tolerance 0.6 \
                -fragment_bin_offset 0.4 \
                -debug 0 \
                > 020320_TiO2_Phospho_comet.log

Command exit status:
  6

Command output:
  (empty)

Command error:
  Parameters passed to 'CometAdapter' are invalid. To prevent usage of wrong defaults, please update/fix the parameters!

Work dir:
  /Volumes/yasset_data/work/protein-expression/PXD018241-phospho/work/6c/c33f267134188babdb31b9e7e94151

**Comment by jpfeuffer** [comment]
Also related: https://github.com/OpenMS/OpenMS/pull/4874

**Comment by jpfeuffer** [comment]
Should work now. One thing to note: the workflow does not support the Comet specific Met-loss N-term cleavage parameter (mainly because other search engines do not support the same -> consistency). The param is different from the modification (since e.g. "double modification" can occur with the parameter but not the modification), the param also would affect coverage calculation slightly..
