### ISSUE TITLE
luciphor2 not found in path of dev container 

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#66]
-- done [took 06:40 m (CPU), 11:23 m (Wall)] -- 
Progress of 'loading chromatogram list':
-- done [took 0.23 s (CPU), 0.58 s (Wall)] -- 
Input file 'luciphor2.jar' could not be found (by searching on PATH). Either provide a full filepath or fix your PATH environment!
Error: File not found (the file 'luciphor2.jar' could not be found)

**Comment by jpfeuffer** [comment]
Seems like the "dev" profile was missing.
