### ISSUE TITLE
When the identification part is only relevant - proteomicslfq fail 

### ISSUE THREAD

**Issue by ypriverol** [nf-core/proteomicslfq#68]
@julianus @timosachsenberg : 

When running the id part only, I guess the proteomicslfq node should only report the protein inference and not the quant part. Currently, I have an error like for this dataset: https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD018241/sdrf-phosphoproteomics.tsv 

g 
File '/homes/pst_prd/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/homes/pst_prd/.OpenMS/OpenMS.ini' with defaults!
Unknown (or deprecated) Parameter 'xtandem_executable' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'omssa_executable' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'temp_dir' overridden: '' --> '/nfs/pride/work/archive/oms-platform/temp/'!
Unknown (or deprecated) Parameter 'swissprot' given in outdated parameter file! Ignoring parameter. 
Default-Parameter 'threads' overridden: '1' --> '2'!
Error: Unexpected internal error ((Fraction Group, Fraction, Label) combination can only appear once)

**Comment by timosachsenberg** [comment]
hmm this sounds more like a problem with experimental design. let me check

**Comment by timosachsenberg** [comment]
maybe this typo? 

comment[technical replcate]
--

**Comment by ypriverol** [comment]
Going for it
