### ISSUE TITLE
New template -> sync

### ISSUE THREAD

**Issue by Zethson** [nf-core/proteomicslfq#7]
tools got a new release and it's time to sync the template again.

I shall trigger sync manually and dig through the conflicts.

Currently busy, but will take this up asap.

**Comment by Zethson** [comment]
I'll fix the unrelated histories from TEMPLATE to dev soon and then create a PR.

**Comment by jpfeuffer** [comment]
Will you remove travis while doing that?

**Comment by Zethson** [comment]
Sure. I'll try to do the template syncing tomorrow or on Sunday.

There's no reason against removing travis, right?
