### ISSUE TITLE
Add experimental design sample dataframe

### ISSUE THREAD

**Issue by javanOkendo** [nf-core/proteomicslfq#98]
Could you add a sample of experimental design. It will provide a roadmap for the users

**Comment by Zethson** [comment]
See here: https://github.com/nf-core/test-datasets/blob/proteomicslfq/testdata/BSA_design.tsv for an example. Here's the corresponding input data: https://github.com/nf-core/test-datasets/tree/proteomicslfq/testdata

**Comment by Zethson** [comment]
I agree however that we should document this properly in the usage section.

**Comment by javanOkendo** [comment]
Thanks

**Comment by Zethson** [comment]
@javanOkendo I'll reopen this to remind us to document this a little bit better.

But glad that you have something that you could use.

Cheers.
